#!/usr/bin/env python3
"""Extrahuje <style> bloky do /css/style.css a scopuje page-specific CSS."""
from __future__ import annotations
import re
from pathlib import Path

PAGES = {
    "index.html": "index",
    "trh.html": "trh",
    "platformy.html": "platformy",
    "eshopari.html": "eshopari",
    "doprava.html": "doprava",
    "sk-vs-eu.html": "sk-vs-eu",
    "onas/index.html": "onas",
    "mediakit/index.html": "mediakit",
    "privacy.html": "privacy",
}

STYLE_RE = re.compile(r"<style>(.*?)</style>", re.DOTALL | re.IGNORECASE)
BODY_OPEN_RE = re.compile(r"<body(\s[^>]*)?>", re.IGNORECASE)
HEAD_CLOSE_RE = re.compile(r"</head>", re.IGNORECASE)
STYLESHEET_LINK = '<link rel="stylesheet" href="/css/style.css">'


def main() -> None:
    root = Path(__file__).resolve().parent.parent
    css_dir = root / "css"
    css_dir.mkdir(exist_ok=True)

    base_css = ""
    page_css_blocks: list[tuple[str, str]] = []
    seen_base = False

    for rel, page_id in PAGES.items():
        p = root / rel
        if not p.exists():
            continue
        html = p.read_text(encoding="utf-8")
        blocks = STYLE_RE.findall(html)
        if not blocks:
            print(f"{rel}: no <style> blocks")
            continue

        print(f"{rel}: {len(blocks)} <style> blocks")
        if not seen_base:
            base_css = blocks[0]
            seen_base = True
            print("  -> used as base")
        for b in blocks[1:]:
            page_css_blocks.append((page_id, b))

    out = [
        "/* =======================================================",
        " * Slovak e-commerce - unified stylesheet",
        " * Generated by scripts/extract_inline_css.py",
        " * ======================================================= */",
        "",
        "/* --- BASE --------------------------------------------- */",
        base_css.strip(),
        "",
    ]
    for page_id, css in page_css_blocks:
        out.append(f"/* --- {page_id.upper()} ----------------------------- */")
        out.append(f'body[data-page="{page_id}"] {{')
        out.append(css.strip())
        out.append("}")
        out.append("")

    (css_dir / "style.css").write_text("\n".join(out), encoding="utf-8")
    print(f"\nWrote css/style.css ({(css_dir / 'style.css').stat().st_size} B)")

    for rel, page_id in PAGES.items():
        p = root / rel
        if not p.exists():
            continue
        html = p.read_text(encoding="utf-8")
        original = html
        html = STYLE_RE.sub("", html)

        def add_data_page(match: re.Match) -> str:
            attrs = match.group(1) or ""
            if "data-page=" in attrs:
                return match.group(0)
            return f'<body{attrs} data-page="{page_id}">'

        html = BODY_OPEN_RE.sub(add_data_page, html, count=1)

        if "/css/style.css" not in html:
            html = HEAD_CLOSE_RE.sub(
                f"    {STYLESHEET_LINK}\n</head>", html, count=1
            )

        if html != original:
            p.write_text(html, encoding="utf-8")
            print(f"  edited: {rel}")


if __name__ == "__main__":
    main()
